# Generated by Django 4.2.9 on 2024-02-03 03:52

from django.db import migrations


def migrate_settings(app, schema_editor):
    Event = app.get_model('pretixbase', 'Event')
    EventSettingsStore = app.get_model('pretixbase', 'Event_SettingsStore')

    for e in Event.objects.all():
        days_entry = EventSettingsStore.objects.filter(object=e, key='mail_days_order_expire_warning').first()

        if days_entry:
            days = days_entry.value
            days_entry.delete()
        else:
            days = 0

        EventSettingsStore.objects.create(object=e, key='mail_hours_order_expire_warning', value = days * 24)


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0273_remove_checkinlist_auto_checkin_sales_channels'),
    ]

    operations = [
        migrations.RunPython(migrate_settings, migrations.RunPython.noop)
    ]
