# Generated by Django 4.2.27 on 2026-01-04 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0274_expiry_days_to_hours'),
        ('pretixbase', '0296_invoice_invoice_from_state'),
    ]

    operations = [
    ]
